### ISSUE TITLE
関数の命名

### ISSUE THREAD

**Issue by naru-jpn** [Handii-inc/HDDelegateButton#8]
#7 の修正を前提にして書いています。こちらの方が重要度が低いので、issue を分離しています。

```swift
    @objc private func doAction(_ sender: UIButton,
                                action methodOrNil: ((UIButton) -> Void)?)
    {
        guard let method = methodOrNil else {
            return  //do nothing
        }
        method(sender)
        return
    }
```

上記の関数の命名に関して、`action` という単語が重複していますので、これを省略して、

```swift
    private func `do`(action: ((UIButton) -> Void)?, with sender: UIButton) {
        action?(sender)
    }
```

と書くことで、より英文のようになります。（できる限り英文のように、という Swift の方向性からです）

ただし `do` は予約語の一つですので、関数名 `do` はバッククォートで囲む必要性が出てきます。これを避けるためには、`do` ではなく `execute` のような単語を使う必要がありますが、この辺りは好みによるのでどちらでもよいと思います。

- 参考
   - [Swift API Design Guidelines (Omit needless words.) ](https://swift.org/documentation/api-design-guidelines/#naming)

---

## （補）関数名に予約語を使う場合と使わない場合の差

上に 

> 単語は好みによる

と書きましたが、1点コード上の違いが出てきます。

### 予約語でない単語を使用した場合

```swift
    private func execute(action: ((UIButton) -> Void)?, with sender: UIButton) {
        action?(sender)
    }
    
    @objc private func touchDownRepeat(sender: UIButton) {   
        execute(action: delegatePointer?.touchDownRepeat, with: sender)
    }
```

### 予約語を使用した場合

```swift
    private func `do`(action: ((UIButton) -> Void)?, with sender: UIButton) {
        action?(sender)
    }
    
    @objc private func touchDownRepeat(sender: UIButton) {   
        self.do(action: delegatePointer?.touchDownRepeat, with: sender)
    }
```

予約語を関数名に用いた場合には、呼び出し時に `self` が必須になります。 `self` は必要な時にのみ書く、という派もありますので、そのような場合は気持ちの悪い `self` が残ることになります。

**Comment by IgnorantCoder** [comment]
@naru-jpn 
こういうケースでよく迷うんですけど、
```
execute(action: ((UIButton) -> Void)?, with sender: UIButton)
```
とするか、
```
execute(_ action: ((UIButton) -> Void)?, with sender: UIButton)
```
です。
前者のほうが関数のフェイスが美しくなるんですが、後者だと呼び出し側が、
```
execute(.touchDownRepeet, with: sender)
```
となって綺麗に見えます。こういうケースでは、最初ご提案いただいたとおり、前者を採用するケースが多いですか？

**Comment by naru-jpn** [comment]
@IgnorantCoder 

いえ、今回は後者です。
今回は `delegatePointer?.touchDownRepeat` が関数だということが明確で、`action` という単語で説明している事と同義なので、後者のように呼び出し側のラベルを省略する形式の方が好ましいと思います。

加えていま思ったのですが、すでに `execute` 関数の中身は1行になっていてやっているのは関数の実行のみなので、 `execute` 関数を介さずに

```
    @objc private func touchDownRepeat(sender: UIButton) {   
        delegatePointer?.touchDownRepeat(sender: sender)
    }
```

としてしまうのが一番簡潔かもしれません。

**Comment by IgnorantCoder** [comment]
@naru-jpn 
そもそもguard文を全部に書くのがうざかっただけなので
```swift
@objc private func touchDownRepeat(sender: UIButton) {   
        delegatePointer?.touchDownRepeat(sender: sender)
    }
```
でいきます。
